"""initial

Revision ID: db96c15578c1
Revises:
Create Date: 2023-09-24 15:23:32.710439

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db96c15578c1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anime",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("episodes", sa.Integer(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("added_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("voice_acting", sa.String(), nullable=True),
        sa.Column("order_by", sa.String(), nullable=True),
        sa.Column("series", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("order_by", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("records", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    op.create_table(
        "games",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("subname", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("records", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("order_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    op.create_table(
        "socials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
        schema="pwsi",
    )
    op.create_table(
        "twitchbot_counters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("name", "type"),
        schema="pwsi",
    )
    op.create_table(
        "twitchbot_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("twitchbot_lists", schema="pwsi")
    op.drop_table("twitchbot_counters", schema="pwsi")
    op.drop_table("socials", schema="pwsi")
    op.drop_table("games", schema="pwsi")
    op.drop_table("challenges", schema="pwsi")
    op.drop_table("anime", schema="pwsi")
    # ### end Alembic commands ###
