"""merch

Revision ID: 91dcb1834daa
Revises: 2a907f0076ed
Create Date: 2024-09-07 12:23:45.394384

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91dcb1834daa"
down_revision: Union[str, None] = "2a907f0076ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("creator_name", sa.String(), nullable=True),
        sa.Column("creator_link", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("picture_size", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merch", schema="pwsi")
    # ### end Alembic commands ###
