"""games gift by

Revision ID: 2a907f0076ed
Revises: 5b4dd6b3307e
Create Date: 2024-06-23 22:05:12.723308

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a907f0076ed"
down_revision: Union[str, None] = "5b4dd6b3307e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("gift_by", sa.String(), nullable=True),
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "gift_by", schema="pwsi")
    # ### end Alembic commands ###
