"""marathons

Revision ID: 7a97f645165d
Revises: 508d95e85ac4
Create Date: 2024-03-13 01:15:47.494110

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a97f645165d"
down_revision: Union[str, None] = "508d95e85ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marathons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("records", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("marathon_id", sa.Integer(), nullable=True),
        sa.Column("steam_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("marathons", schema="pwsi")
    # ### end Alembic commands ###
