"""cinema

Revision ID: 4c2c61360f34
Revises: 1a7ea21d399f
Create Date: 2025-10-26 23:29:50.024774

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c2c61360f34"
down_revision: Union[str, None] = "1a7ea21d399f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cinema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("subname", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("order_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cinema", schema="pwsi")
    # ### end Alembic commands ###
