"""picture mode

Revision ID: 1a7ea21d399f
Revises: f0f0c718c11a
Create Date: 2025-05-24 15:28:17.657085

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a7ea21d399f"
down_revision: Union[str, None] = "f0f0c718c11a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column(
        "anime",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="pwsi",
    )
    conn.execute(sa.text("UPDATE pwsi.anime SET picture_mode='portrait';"))
    op.alter_column(
        "anime",
        "picture_mode",
        existing_type=sa.String(),
        nullable=False,
        schema="pwsi",
    )

    op.add_column(
        "challenges",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="pwsi",
    )
    conn.execute(sa.text("UPDATE pwsi.challenges SET picture_mode='landscape';"))
    op.alter_column(
        "challenges",
        "picture_mode",
        existing_type=sa.String(),
        nullable=False,
        schema="pwsi",
    )

    op.add_column(
        "games",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="pwsi",
    )
    conn.execute(sa.text("UPDATE pwsi.games SET picture_mode='landscape';"))
    op.alter_column(
        "games",
        "picture_mode",
        existing_type=sa.String(),
        nullable=False,
        schema="pwsi",
    )

    op.add_column(
        "marathons",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="pwsi",
    )
    conn.execute(sa.text("UPDATE pwsi.marathons SET picture_mode='landscape';"))
    op.alter_column(
        "marathons",
        "picture_mode",
        existing_type=sa.String(),
        nullable=False,
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marathons", "picture_mode", schema="pwsi")
    op.drop_column("games", "picture_mode", schema="pwsi")
    op.drop_column("challenges", "picture_mode", schema="pwsi")
    op.drop_column("anime", "picture_mode", schema="pwsi")
    # ### end Alembic commands ###
