"""float anime score

Revision ID: 332e884f70c3
Revises: 4c2c61360f34
Create Date: 2026-09-02 21:58:05.595334

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "332e884f70c3"
down_revision: Union[str, None] = "4c2c61360f34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anime",
        "score",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="pwsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anime",
        "score",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="pwsi",
    )
    # ### end Alembic commands ###
